# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: springsin0's Homepage/Blog
author: springsin0
email: 
description: > # this means to ignore newlines until "baseurl:"
  気まぐれ
url: https://springsin0.github.io # the base hostname & protocol for your site, e.g. http://example.com
domainurl: https://springsin0.github.io
sitesearchurl: springsin0.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Markdown Processors
markdown: kramdown

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/pages:num/"

mathjax: false

excerpt_separator: <!-- more -->

#permalink: /:categories/:title.html
#permalink: /:categories/:year-:month-:day-:title.html
permalink: /blog/:year-:month-:day-:title:output_ext

#permalink: /blog/:year-:month-:day-:title

pages:
  permalink: :path/:basename:output_ext
  
social_media:
  github_url: https://github.com/springsin0
  weibo_url: http://weibo.com/u/
  zhihu_url: https://www.zhihu.com/people/
  twitter_url: https://twitter.com/
  lofter_url: http://.lofter.com/

#这个指的是生成的网页上要显示什么时间，md文件front matter里不写+0800的话，不管这里怎么设置jekyll一律认为那个是UTC时间。
timezone: Asia/Shanghai
#timezone: Japan
#timezone: UTC

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.bak"
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  # -
    # scope:
      # path: "projects"
      # type: "pages" # previously `page` in Jekyll 2.2.
    # values:
      # layout: "project" # overrides previous default layout
      # author: "Mr. Hyde"

  
